name: Test and deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  deployToGitHubPages:
    name: test and deploy BuildKite-Monitor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: install & lint
        run: |
          yarn install && yarn lint
      - name: E2E
        run: |
          docker-compose up --build e2e
      - name: build project
        run: |
          yarn build
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: guzhongren
          user_email: guzhongren@live.cn
      - name: UI Automation Test
        run: sleep 60 && yarn cy:run
      - name: Trivy scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'powerboard_web'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      # - name: Trivy scanner
      # run: |Trivy scanner for images
      #   docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      #     aquasec/trivy image --severity HIGH,CRITICAL --exit-code 1 dashboard:${{ github.sha }}
